---

version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Load dependencies
          command: |
            mvn --batch-mode dependency:resolve-plugins dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Deploy
          command: |
            mvn --batch-mode --settings ./.circleci/settings.xml deploy
